version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.59.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
      - run:
          name: Hello world publisher
          background: true
          command: cargo run --example hello_world_publisher
      - run:
          name: Hello world subscriber
          no_output_timeout: 10s
          command: cargo run --example hello_world_subscriber