version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
      - run:
          name: Hello world example
          command: |
            cargo run --example hello_world_publisher &
            cargo run --example hello_world_subscriber | grep 'Msg: "Hello world!"'