[package]
name = "dds"
version = "0.1.0"
authors = ["Joao Rebelo <jrebelo@s2e-systems.com>",
		   "Stefan Kimmer <skimmer@s2e-systems.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dds-api = {path="../dds_api"}
dds-implementation = {path="../dds_implementation"}
dds_derive = {path="../dds_derive"}
rtps-implementation = {path="../rtps_implementation"}
rtps-pim = {path="../rtps_pim"}
rtps-udp-psm = {path="../rtps_udp_psm"}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
cdr = "0.2"

byteorder = "1.4.3"
socket2 = "0.4"
erased-serde = "0.3"
ifcfg = "0.1"
mac_address = "1.1"

[dependencies.async-std]
version = "1.7.0"
features = ["unstable"]

[dev-dependencies]
mockall = {version = "0.11"}