[package]
name = "rust-dds"
version = "0.1.0"
authors = ["Joao Rebelo <jrebelo@s2e-systems.com>",
		   "Stefan Kimmer <skimmer@s2e-systems.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-dds-api = {path="../dds_api"}
rust-dds-rtps-implementation = {path="../dds_rtps_implementation"}
rust-rtps-pim = {path="../rtps_pim"}
rust-rtps-udp-psm = {path="../rtps_udp_psm"}

serde_json = "1.0.64"

byteorder = "1.4.3"
socket2 = "0.4"
erased-serde = "0.3"

[dependencies.async-std]
version = "1.7.0"
features = ["unstable"]

[dev-dependencies]
mockall = {version = "0.10.2"}