[package]
name = "dust_dds"
version = "0.1.0"
authors = [
	"Joao Rebelo <jrebelo@s2e-systems.com>",
	"Stefan Kimmer <skimmer@s2e-systems.com>",
	"Pierre Martinet <pmartinet@s2e-systems.com>"
]
license = "Apache-2.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
cdr = "0.2.4"

derive_more = "0.99.16"
md5 = "0.7.0"  # Chose this crate over other possibilities since it doesn't have any other dependencies

byteorder = "1.4.3"
lazy_static = "1.4"

socket2 = "0.4"
ifcfg = "0.1"
mac_address = "1.1"

jsonschema = "0.16"
serde_json = "1.0.87"
schemars = "0.8.11"

[dev-dependencies]
dust_dds_derive = { path = "../dds_derive" }
mockall = { version = "0.11" }
