[package]
name = "dds_derive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = "1.0"

[dev-dependencies]
cdr = "0.2"
dds = { path = "../dds" }
serde = { version = "1.0", features = ["derive"] }
