[package]
name = "dds_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = "1.0"

[dev-dependencies]
cdr = "0.2"
dds = { path = "../dds" }
serde = { version = "1.0", features = ["derive"] }
